idil/basic_app/urls.py
from django.urls import path,include
from basic_app import views

app_name='basic_app'
urlpatterns = [
    path('',views.login_register,name='login_register'),
    path('index/',views.index,name='index'),
    path('manage_acc/<username>',views.acc,name='acc'),
    path('upload/<username>',views.upload,name='upload'),
    path('save/<username>',views.save,name='save'),
    path('change/<username>',views.change,name='change'),
    path('update/<username>',views.update,name='update'),
    path('show/<username>',views.show,name='show'),
    path('apply/<username>',views.apply,name='apply'),
    path('logout',views.user_logout,name='user_logout'),
]

idil/idil/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user_admin import views1
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
    path('user_admin/',include('user_admin.urls')),
    path('user_admin/<username>/',views1.index,name='admin'),
    path('home/<username>/',views.home,name='user'),
    path('accounts/login/',views.login_register,name='login')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idil/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from uuid import uuid4

def path_and_rename(instance, filename):
    upload_to = 'profile_pics'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)
# Create your models here.

class UserDetail(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    role=models.CharField(max_length=128,default='employee')
    profile_pic=models.ImageField(upload_to=path_and_rename,blank=True,null=True)
    last_login = models.DateTimeField(blank=True,null=True)
    def __str__(self):
        return self.user.username

idil/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserDetail

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password*','class':"form-control"}))
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter username*','class':"form-control"}))
    first_name = forms.CharField(max_length=75, required=True,widget= forms.TextInput(attrs={'placeholder':'Enter your first name*','class': "form-control"}))
    last_name=forms.CharField(max_length=75,required=False,widget= forms.TextInput(attrs={'placeholder':'Enter your Last name','class': "form-control"}))
    email = forms.CharField(max_length=75, required=True,widget= forms.TextInput(attrs={'placeholder':'Enter email address*','class': "form-control"}))
    class Meta():
        model=User
        fields=('username','first_name','last_name','email','password')
       

class UserDetailForm(forms.ModelForm):
    profile_pic=forms.ImageField(required=False)
    class Meta():
        model=UserDetail
        fields=('profile_pic',)

idil/basic_app/views.py
from django.shortcuts import render,redirect
from .forms import UserForm,UserDetailForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from .models import User,UserDetail
from user_admin.models import UserAdmin,Challenges,AppliedChallenges
from idil import settings
import os
import cv2
# Create your views here.
@login_required
def home(request,username):
    context={}
    print(username+'sjh')
    user_list=User.objects.all()
    challenges=Challenges.objects.all()
    ac=AppliedChallenges.objects.all()
    context['challenges']=challenges
    appl=True
    p=0
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            users=UserDetail.objects.all()
            for user2 in users:
               if str(user2)==str(username):
                   context['usd']=user2
    for c in challenges:
        for a in ac:
            if str(a.challenge)==str(c.name) and str(a.user)==str(context['usr']):
                p=a.points
                appl=False
                break
    context['a']=appl
    context['p']=p
    return render(request,'basic_app/home.html',context)

@login_required
def acc(request,username):
    user_list=User.objects.all()
    context={}
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            user_detail_list=UserDetail.objects.all()
            for user2 in user_detail_list:
               if str(user2)==str(username):
                   context['usd']=user2
    return render(request,'basic_app/acc.html',context)


@login_required
def upload(request,username):
    user_list=User.objects.all()
    context={}
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            user_details_list=UserDetail.objects.all()
            for user2 in user_details_list:
               if str(user2)==str(username):
                   context['usd']=user2
    if request.method=="POST":
        if len(request.FILES)!=0:
           img = request.FILES['pic']
           img_extension = os.path.splitext(img.name)[1]
           s=settings.MEDIA_ROOT
           s=os.path.join(s, 'profile_pics')
           if context['usd'].profile_pic:
                c=str(context['usd'].profile_pic).split("/")[1]
                k=os.path.join(s,c)
                print("ghxc")
                if os.path.exists(k):
                    os.remove(k)
                    context['usd'].profile_pic=request.FILES['pic']
                    context['usd'].save()
                    return render(request,'basic_app/acc.html',context)
           else:
                print("Image not there")
                context['usd'].profile_pic=request.FILES['pic']
                context['usd'].save()
    return render(request,'basic_app/acc.html',context)
@login_required
def save(request,username):
    user_list=User.objects.all()
    context={}
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            user_detail_list=UserDetail.objects.all()
            for user2 in user_detail_list:
               if str(user2)==str(username):
                   context['usd']=user2
    if request.method=="POST":
        context['usr'].email=request.POST.get('email')
        context['usr'].save()
    return render(request,'basic_app/acc.html',context)

@login_required
def update(request,username):
    user_list=User.objects.all()
    context={}
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            user_detail_list=UserDetail.objects.all()
            for user2 in user_detail_list:
               if str(user2)==str(username):
                   context['usd']=user2
    if request.method=="POST":
        context['usr'].first_name=request.POST.get('fn')
        context['usr'].last_name=request.POST.get('ln')
        context['usr'].save()
    return render(request,'basic_app/acc.html',context)

@login_required
def change(request,username):
    user_list=User.objects.all()
    context={}
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            user_detail_list=UserDetail.objects.all()
            for user2 in user_detail_list:
               if str(user2)==str(username):
                   context['usd']=user2
    if request.method=="POST":
        user1=authenticate(username=username,password=request.POST.get('op'))
        if user1==None:
            context['er']=True
        else:
            if request.POST.get('op')==request.POST.get('np'):
                context['dm']=True
            else:
                context['usr'].set_password(request.POST.get('np'))
                context['usr'].save()
    return render(request,'basic_app/acc.html',context)


@login_required
def user_logout(request):
    #request.session.flush()
    logout(request)
    return redirect('/')

def index(request):
    context={}
    context['name']='Saikat'
    # user_form=UserForm(data=request.POST)
    # user_detail_form=UserDetailForm(data=request.POST)
    # context['user_form']=user_form
    # context['user_detail_form']=user_detail_form
    return render(request,'basic_app/index.html',context)

def login_register(request):
    show_div=False
    print(request.method)
    if request.GET.get('login'):
        show_div=False
    elif request.GET.get('reg'):
        show_div=True
    context={}
    context['error']=False
    user_form=UserForm(data=request.POST)
    user_detail_form=UserDetailForm(data=request.POST)
    user_detail1=UserDetail
    if request.method == "POST" and show_div:
        print(user_form.is_valid())
        print(user_detail_form.is_valid())
        if user_form.is_valid() and user_detail_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user_detail=user_detail_form.save(commit=False)
            user_detail.user=user
            if len(request.FILES)!=0:
                p=request.FILES['profile_pic']
                p=str(p)
                print(p)
                if p.endswith('.jpg') or p.endswith('.jpeg') or p.endswith('.png'):
                    user_detail.profile_pic=request.FILES['profile_pic']
                    user.save()
                    user_detail.save()
                    request.session['username']=user.username
                    login(request,user)
                    return redirect('/basic_app/home')
                else:
                    context['show_div']=True
                    context['user_form']=user_form
                    context['user_detail_form']=user_detail_form
                    context['warning']=True
                    return render(request,'basic_app/login.html',context)
            else:
                user.save()
                user_detail.save()
                request.session['username']=user.username
                login(request,user)
                return redirect('/basic_app/home')
           
    elif request.method == "POST" and not show_div:
       username=request.POST.get('username')
       password=request.POST.get('password')
       user1=authenticate(username=username,password=password)

       if user1!=None:
           user_detail_list=UserDetail.objects.all()
           ef=False
           for user2 in user_detail_list:
               if str(user2)==str(user1):
                   ef=True
                   break
           user_admin_list=UserAdmin.objects.all()
           af=False
           for user2 in user_admin_list:
               if str(user2)==str(user1):
                   print(user2)
                   af=True
                   break
           request.session['username']=user1.username
           if af:
             u=str(user1)
             url = reverse('admin', kwargs={'username': u})
             print(url)
             login(request,user1)
             return HttpResponseRedirect(url)
           elif ef:
                u=str(user1)
                url = reverse('user', kwargs={'username': u})
                login(request,user1)
                return HttpResponseRedirect(url)
       else:                                                                         
           context['error']=True
    context['user_form']=user_form
    context['user_detail_form']=user_detail_form
    context['show_div']=show_div
    return render(request,'basic_app/login.html',context)

@login_required
def show(request,username):
    c_name=username.split('_')[1]
    print(c_name)
    username=username.split("_")[0]
    challenges=Challenges.objects.all()
    ac=AppliedChallenges.objects.all()
    appl=True
    context={}
    for c in challenges:
        if str(c)==c_name:
           context['ch']=c
    user_list=User.objects.all()
    for u in user_list:
        if str(u)==str(username):
            user_info=u
            context['usr']=user_info
            user_detail_list=UserDetail.objects.all()
            for user2 in user_detail_list:
               if str(user2)==str(username):
                   context['usd']=user2
    for a in ac:
        if str(a.challenge)==str(context['ch']) and str(a.user)==str(context['usr']):
            appl=False
            break
    context['a']=appl
    return render(request,'basic_app/show.html',context)
 
@login_required
def apply(request,username):
    print(username)
    u=username.split("_")[0]
    c=username.split("_")[1]
    a=AppliedChallenges()
    n=0
    challenges=Challenges.objects.all()
    for ca in challenges:
        if str(ca.name)==c:
            n=ca.applicant
            break
    n=n+1

idil/templates/basic_app/acc.html
{%extends "basic_app/user_base.html" %}
{% load static %}
{% block body_block %}
<header class="header">

    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">

            <a href="/home/{{usr.username}}" class="navbar-brand">
                <img src="/static/img/logo.svg" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>

                
                <ul class="navbar-nav ml-auto">
                    <li id="navHone" class="nav-item ">
                        <a href="/home/{{usr.username}}" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li id="navBoard" class="nav-item">
                        <a href="/manage_acc/{{usr.username}}" class="nav-link">My Account</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li id="navuser2" class="nav-item " style="color: #fff">
                            <a href="{% url 'basic_app:user_logout' %}"class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Logout
                            </a>
                        </li>
                    {% endif %}
                </ul>         
            </div>
        </div>
    </nav>
</header>
<div class="vd_content-section clearfix">
            <div class="row">
              <div class="col-sm-12">
                <div class="panel widget light-widget">
                  <div class="panel-heading no-title"> </div>
                    <div  class="panel-body">
                      <h2 class="mgbt-xs-20"> Profile: <span class="font-semibold">{{usr.first_name}} {{usr.last_name}}</span> </h2>
                      <br/>
                      <div class="row">
                        <div class="col-sm-3 mgbt-xs-20">
                          <div class="form-group">
                            <div class="col-xs-12">
                              <div class="form-img text-center mgbt-xs-15"> <img alt="example image" src="/media/{{usd.profile_pic}}" style="width:75%; height:50%"> </div>
                              <hr>
                                <form action="/upload/{{usr.username}}" method="POST" enctype="multipart/form-data">
                                   {% csrf_token %}
                                    <div class="form-img-action text-center mgbt-xs-20"> 
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="upload" name="pic" type="file"/><hr>
                                        <input type="submit" class="btn vd_btn  vd_bg-blue" id="upload_link" value="upload"><i class="fa fa-cloud-upload append-icon"></i>
                                    </div>
                                </form>
                              <br/>
                             
                            </div>
                          </div>
                        </div>
                        <div class="col-sm-9">
                          <h3 class="mgbt-xs-15">Account Setting</h3>
                          <form action="/save/{{usr.username}}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control" name="uname" value={{usr.username}}>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control" name="email" value={{usr.email}} >
                                </div>
                            </div>
                         
                            <input type="submit" class="btn btn-success" value="Save">
                         </form>
                            <hr>
                             <h3 class="mgbt-xs-15">Change Password</h3>
                            <form action="/change/{{usr.username}}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Old Password</label>
                                <div class="col-sm-8">
                                <input type="password" class="form-control"  id="pass_input"  name="op" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">New Password</label>
                                <div class="col-sm-8">
                                <input type="password" class="form-control" id="pass_input1" name="np" required>
                                </div>
                            </div>
                            <input type="submit" class="btn btn-success" id="register" value="Change Password" >
                                    {% if  er%}
                                        <span style="color:red">Old Password is not correct</span>
                                    {% endif %}
                                    {% if  dm%}
                                        <span style="color:red">Both Password are equal</span>
                                    {% endif %}
                            </form>
                            <br>
                            <p style="color:red">N.B:- After Succesful Password Change You have to Re Login</p>
                          <hr>
                          <h3 class="mgbt-xs-15">Profile Setting</h3>
                          <form action="/update/{{usr.username}}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">First Name</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control" id="inputPassword" name="fn" value="{{usr.first_name}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Last Name</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control" id="inputPassword" name="ln" value="{{usr.last_name}}" >
                                </div>
                            </div>
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                        </div>
                      
                    </div>
                    <!-- panel-body -->
                    </div>
                </div>
                <!-- Panel Widget --> 
              </div>
              <!-- col-sm-12--> 
            </div>
            <!-- row --> 
            
</div>
          <!-- .vd_content-section --> 
<hr>
{% endblock %}

idil/templates/basic_app/index.html
{% load static %}
Welcome Mr. {{name}}
<div style="position:center">
    <img src="{% static 'images/1.jpg' %}">
</div>

idil/templates/basic_app/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
		<script type="text/javascript" src="{% static 'js/modernizr.custom.86080.js' %}"></script>
    </head>
    <body>
    
        <ul class="cb-slideshow">
            <li><span>Image 01</span><div></div></li>
            <li><span>Image 02</span><div></div></li>
            <li><span>Image 03</span><div></div></li>
            <li><span>Image 04</span><div></div></li>
            <li><span>Image 05</span><div></div></li>
            <li><span>Image 06</span><div></div></li>
        </ul>

       {% if show_div %}
       
        <br>
        <br>
        <br>
        <div class="container register">
                <div class="row">
                    <div class="col-md-3 register-left">
                        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
                        <h3>Welcome</h3>
                        <form action="{% url 'basic_app:login_register'%}" method="get">
                            <input type="submit" id="login" name="login" value="Login"/><br/>
                        </form>
                    </div>
                    <div class="col-md-9 register-right">
                        
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <h1 class="register-heading"><b>Fill the Details Below</b></h1>
                                <form method="POST" enctype="multipart/form-data">
                                   {% csrf_token %}
                                 <div class="row register-form">
                                    <div class="col-md-6">
                                        <div class="form-group"> 
                                            {{ user_form.first_name }}
                                           
                                        </div>
                                        <div class="form-group">
                                            
                                        </div>
                                        <div class="form-group">
                                            {{ user_form.username }}
                                        </div>
                                        <div class="form-group">
                                           {{ user_form.password}}
                                        </div>
                                        <div class="form-group">
                                           
                                        </div>
                                        
                                           
                                    </div>
                                     
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            {{ user_form.last_name }}
                                        </div>
                                        <div class="form-group">
                                           {{ user_form.email }}
                                        </div>
                                    </div>
                                     &nbsp;&nbsp;&nbsp;&nbsp;<p> Upload Profile Photo{{ user_detail_form.profile_pic }}
                                     {% if not warning %}
                                        <span style='color:red; font-size:11px'>supported files *jpg,*jpeg,*png</span>
                                    
                                     {% else %}
                                        <span style='color:red; font-size:11px'>Unsupported file uploaded</span>
                                     {%endif%}
                                     </p>
                                    <div class="col-md-8"> 
                                        <input type="submit" class="btnRegister"  value="Register"/>
                                    </div>
                                 </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
           

            {% else %}
            <br>
            <br>
            <br>
            <br>
            <div class="container register">
                <div class="row">
                    <div class="col-md-3 register-left">
                        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
                        <h3>Welcome</h3>
                        <form action="{% url 'basic_app:login_register'%}" method="get">
                        <input type="submit" name="reg" value="Register"/><br/>
                        </form>
                    </div>
                    <div class="col-md-9 register-right">
                        
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <h3 class="register-heading"><b>Enter Your Credentials</b></h3>
                                <form method="POST" action="{% url 'basic_app:login_register'%}">
                                    {% csrf_token %}
                                    <div class="row register-form">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input type="text" name="username" class="form-control" required placeholder="Enter your username">
                                                
                                            </div>
                                            <div class="form-group">
                                                <input type="password" name="password" class="form-control" required  placeholder="Enter your password">
                                            </div>
                                            {% if error %}
                                                <span style='color:red'>  Username or Password Invalid</span>
                                            {% endif %}
                                        </div>
                                        
                                        <div class="col-md-8"> 
                                            <input type="submit" class="btnRegister"  value="Login"/>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
             {% endif %} 


    </body>

</html>