idil/basic_app/urls.py
from django.urls import path,include
from basic_app import views

app_name='basic_app'
urlpatterns = [
    path('',views.login_register,name='login_register'),
    path('index/',views.index,name='index'),
    path('manage_acc/<username>',views.acc,name='acc'),
    path('upload/<username>',views.upload,name='upload'),
    path('save/<username>',views.save,name='save'),
    path('change/<username>',views.change,name='change'),
    path('update/<username>',views.update,name='update'),
    path('show/<username>',views.show,name='show'),
    path('apply/<username>',views.apply,name='apply'),
    path('logout',views.user_logout,name='user_logout'),
]

idil/idil/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user_admin import views1
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
    path('user_admin/',include('user_admin.urls')),
    path('user_admin/<username>/',views1.index,name='admin'),
    path('home/<username>/',views.home,name='user'),
    path('accounts/login/',views.login_register,name='login')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idil/user_admin/urls.py
from django.urls import path,include
from user_admin import views1

app_name='user_admin'
urlpatterns = [
     path('acc/<username>',views1.acc,name='acc'),
     path('upload/<username>',views1.upload,name='upload'),
     path('save/<username>',views1.save,name='save'),
     path('change/<username>',views1.change,name='change'),
     path('update/<username>',views1.update,name='update'),
     path('add/<username>',views1.add,name="add"),
     path('save_challenge/<username>',views1.save_challenge,name="save_challenge"),
     path('edit/<username>',views1.edit,name='edit'),
     path('show/<username>',views1.show,name='show'),
     path('delete/<username>',views1.delete,name='delete'),
     path('admin_logout/',views1.user_logout,name='admin_logout'),
     path('applicants/<username>',views1.applicants,name='applicants'),
     path('complete/<username>',views1.complete,name='complete')
]

idil/user_admin/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from uuid import uuid4
import datetime

def path_and_rename(instance, filename):
    upload_to = 'profile_pics'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)
# Create your models here.
def o():
    return "NOT FILLED"
class UserAdmin(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    role=models.CharField(max_length=128,default='admin')
    profile_pic=models.ImageField(upload_to=path_and_rename,blank=True,null=True)
    last_login = models.DateTimeField(blank=True,null=True)
    def __str__(self):
        return self.user.username
        
class Challenges(models.Model):
    name=models.CharField(primary_key=True,max_length=255)
    technology=models.CharField(max_length=255)
    account=models.CharField(max_length=255)
    capability=models.CharField(max_length=255)
    applicant_status=models.CharField(max_length=255,default="NOT FILLED")
    date_posted=models.DateField(default=datetime.date.today)
    expiry_date=models.DateField()
    applicant=models.IntegerField(default=0)
    manager=models.CharField(max_length=255)
    owner=models.CharField(max_length=255)
    desc=models.CharField(max_length=255)
    points=models.IntegerField()
    category=models.CharField(max_length=255)

    def __str__(self):
        return self.name
class AppliedChallenges(models.Model):
    user=models.CharField(max_length=255)
    challenge=models.CharField(max_length=255)
    completed=models.BooleanField(default=False)
    points=models.IntegerField(default=0)

    def __str__(self):
        return self.user+'_'+self.challenge

idil/templates/user_admin/acc.html
{%extends "user_admin/admin_base.html" %}
{% load static %}
{% block body_block %}
<header class="header">

    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">

            <a href="/user_admin/{{usr.username}}" class="navbar-brand">
                <img src="/static/img/logo.svg" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>

                
                <ul class="navbar-nav ml-auto">
                    <li id="navHone" class="nav-item ">
                        <a href="/user_admin/{{usr.username}}" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li id="navChallenge" class="nav-item">
                        <a href="/user_admin/add/{{usr.username}}" class="nav-link">Add New Challenges</a>
                    </li>
                    <li id="navBoard" class="nav-item">
                        <a href="/user_admin/acc/{{usr.username}}" class="nav-link">My Account</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li id="navuser2" class="nav-item " style="color: #fff">
                            <a href="{% url 'basic_app:user_logout' %}"class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Logout
                            </a>
                        </li>
                    {% endif %}
                </ul>         
            </div>
        </div>
    </nav>
</header>
<div class="vd_content-section clearfix">
            <div class="row">
              <div class="col-sm-12">
                <div class="panel widget light-widget">
                  <div class="panel-heading no-title"> </div>
                    <div  class="panel-body">
                      <h2 class="mgbt-xs-20"> Profile: <span class="font-semibold">{{usr.first_name}} {{usr.last_name}}</span> </h2>
                      <br/>
                      <div class="row">
                        <div class="col-sm-3 mgbt-xs-20">
                          <div class="form-group">
                            <div class="col-xs-12">
                              <div class="form-img text-center mgbt-xs-15"> <img alt="example image" src="/media/{{uad.profile_pic}}" style="width:75%; height:50%"> </div>
                              <hr>
                                <form action="/user_admin/upload/{{usr.username}}" method="POST" enctype="multipart/form-data">
                                   {% csrf_token %}
                                    <div class="form-img-action text-center mgbt-xs-20"> 
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="upload" name="pic" type="file"/><hr>
                                        <input type="submit" class="btn vd_btn  vd_bg-blue" id="upload_link" value="upload"><i class="fa fa-cloud-upload append-icon"></i>
                                    </div>
                                </form>
                              <br/>
                             
                            </div>
                          </div>
                        </div>
                        <div class="col-sm-9">
                          <h3 class="mgbt-xs-15">Account Setting</h3>
                          <form action="/user_admin/save/{{usr.username}}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
                                <div class="col-sm-8">
                                <input type="text" readonly class="form-control" name="uname" value={{usr.username}}>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control" name="email" value={{usr.email}} >
                                </div>
                            </div>
                         
                            <input type="submit" class="btn btn-success" value="Save">
                         </form>
                            <hr>
                             <h3 class="mgbt-xs-15">Change Password</h3>
                            <form action="/user_admin/change/{{usr.username}}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Old Password</label>
                                <div class="col-sm-8">
                                <input type="password" class="form-control"  id="pass_input"  name="op" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">New Password</label>
                                <div class="col-sm-8">
                                <input type="password" class="form-control" id="pass_input1" name="np" required>
                                </div>
                            </div>
                            <input type="submit" class="btn btn-success" id="register" value="Change Password" >
                                    {% if  er%}
                                        <span style="color:red">Old Password is not correct</span>
                                    {% endif %}
                                    {% if  dm%}
                                        <span style="color:red">Both Password are equal</span>
                                    {% endif %}
                            </form>
                            <br>
                            <p style="color:red">N.B:- After Succesful Password Change You have to Re Login</p>
                          <hr>
                          <h3 class="mgbt-xs-15">Profile Setting</h3>
                          <form action="/user_admin/update/{{usr.username}}" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">First Name</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control" id="inputPassword" name="fn" value="{{usr.first_name}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Last Name</label>
                                <div class="col-sm-8">
                                <input type="text" class="form-control" id="inputPassword" name="ln" value="{{usr.last_name}}" >
                                </div>
                            </div>
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                        </div>
                      
                    </div>
                    <!-- panel-body -->
                    </div>
                </div>
                <!-- Panel Widget --> 
              </div>
              <!-- col-sm-12--> 
            </div>
            <!-- row --> 
            
</div>
          <!-- .vd_content-section --> 
<hr>
{% endblock %}

idil/templates/user_admin/add.html
{%extends "user_admin/admin_base.html" %}
{% load static %}
{% block body_block %}
<header class="header">

    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">

            <a href="/user_admin/{{usr.username}}" class="navbar-brand">
                <img src="/static/img/logo.svg" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>

                
                <ul class="navbar-nav ml-auto">
                    <li id="navHone" class="nav-item ">
                        <a href="/user_admin/{{usr.username}}" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li id="navChallenge" class="nav-item">
                        <a href="/user_admin/add/{{usr.username}}" class="nav-link">Add New Challenges</a>
                    </li>
                    <li id="navBoard" class="nav-item">
                        <a href="/user_admin/acc/{{usr.username}}" class="nav-link">My Account</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li id="navuser2" class="nav-item " style="color: #fff">
                            <a href="{% url 'basic_app:user_logout' %}"class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Logout
                            </a>
                        </li>
                    {% endif %}
                </ul>         
            </div>
        </div>
    </nav>
</header>
<br>
<div class="card text-center" style="width:80%; margin-left : 10%">
  <div class="card-header" style="color:red">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Add New Challenges</b>
  </div>
  <div class="card-body" >
    <form method="POST" action="/user_admin/save_challenge/{{usr.username}}">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Challenge Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword" name="cn" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Technology</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="tech" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Account</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="acc" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Capability</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="cap" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Digital Points</label>
            <div class="col-sm-4">
                <input type="number" class="form-control" id="inputPassword" name="points" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Expiry Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" id="inputPassword" name="edate" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Challenge Category</label>
                <div class="col-sm-4">
                    <select class="form-control" id="inlineFormCustomSelectPref" name="cat">
                        <option value="WORKING" selected>WORKING</option>
                        <option value="LEARNING">LEARNING</option>
                    </select>
                </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Manager</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="manager" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Product Owner</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="powner" required>
            </div>
        </div>
        <div class="form-group row">
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label for="inputPassword" class="col-sm-2 col-form-label" >Project Description</label>
            <textarea class="form-control"  style="width:81%" id="exampleFormControlTextarea1" rows="3" name="desc" placeholder="Challenge Description" required></textarea>
        </div>
        
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" class="btn btn-outline-primary" value="ADD">
        
    </form>
  </div>
</div>
<br>
{% endblock %}

idil/templates/user_admin/admin_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>iDIL</title>
    <meta name="description" content="">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/faviocon.png"  type="image/x-icon">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet"
          href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
          href="/static/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <!-- owl carousel-->
    <link rel="stylesheet"
          href="/static/vendor/owl.carousel/assets/owl.carousel.css">
    <link rel="stylesheet"
          href="/static/vendor/owl.carousel/assets/owl.theme.default.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/static/css/style.default.css"
          id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/static/css/custom.css">
    <link rel="stylesheet" href="/static/css/add.css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/static/vendor/bootstrap-select/css/bootstrap-select.min.css">
    <script src="https://code.jquery.com/jquery-migrate-3.3.1.js" integrity="sha256-lGuUqJUPXJEMgQX/RRaM6mZkK6ono5i5bHuBME4qOCo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js" integrity="sha512-wxLJoyhMdb3r9t00CpwvDsbgnHongW0fzpEKS2Y0X2H+ThyUd0AhHVD1/SH37RGSE2/krrzpU+71E37X7UV+4w==" crossorigin="anonymous"></script>
    
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>

</head>
<body>
    {%  block body_block %}
    {% endblock %}
    <footer class="footer">
    <div class="footer__block">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 mb-5">
                    <h4 class="h5">About iDIL</h4>
                    <p> Challenges that make a difference </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-9 text-md-left text-center">
                    <p>&copy;2020  iDil - Digital Innovation & Consulting (IBS Software) &emsp;&emsp;&emsp;&emsp; v: 2.0</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<script type='text/javascript'>
$(document).ready(function() {
    var table = $('#example').DataTable( {
        lengthChange: false,
        buttons: [ 'copy', 'excel', 'pdf', 'colvis' ]
    } );
 
    table.buttons().container()
        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
} );
</script>
<script src="/static/vendor/popper.js/umd/popper.min.js"></script>
<script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.js' %}"></script>
<script src="/static/js/front.js"></script>
<script src="/static/js/custom.js"></script>
</body>

idil/templates/user_admin/applicants.html
{%extends "user_admin/admin_base.html" %}
{% load static %}
{% block body_block %}
<header class="header">

    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">

            <a href="/user_admin/{{usr.username}}" class="navbar-brand">
                <img src="/static/img/logo.svg" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>

                
                <ul class="navbar-nav ml-auto">
                    <li id="navHone" class="nav-item ">
                        <a href="/user_admin/{{usr.username}}" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li id="navChallenge" class="nav-item">
                        <a href="/user_admin/add/{{usr.username}}" class="nav-link">Add New Challenges</a>
                    </li>
                    <li id="navBoard" class="nav-item">
                        <a href="/user_admin/acc/{{usr.username}}" class="nav-link">My Account</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li id="navuser2" class="nav-item " style="color: #fff">
                            <a href="{% url 'user_admin:user_logout' %}"class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Logout
                            </a>
                        </li>
                    {% endif %}
                </ul>         
            </div>
        </div>
    </nav>
</header>
<br>
<div class="card text-center" style="width:80%; margin-left : 10%">
  <div class="card-header" style="color:red;font-size:200%">
    <b>Challenge : {{ch.name}}</b>
  </div>
  <div class="card-body">
        <h3>List of Applicants</h3>
        <table id="example" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th class="th-sm">First Name

      </th>
      <th class="th-sm">Last Name

      </th>
      <th class="th-sm">Email

      </th>
      {% comment %} <th class="th-sm">Completed

      </th> {% endcomment %}
    </tr>
  </thead>
  <tbody>
    {%for p in o %}
        <tr>
            <td>{{p.first_name}}</td>
            <td>{{p.last_name}}</td>
            <td>{{p.email}}</td>
             {% comment %} <td><a href="/user_admin/complete/{{usr.username}}_{{ch.name}}_{{p}}">COMPLETED</a></td> {% endcomment %}
        
        </tr>
    {% endfor %}
  </tbody>
</table>
  </div>
</div>
<br>
<script type='text/javascript'>
$(document).ready(function() {
    var table = $('#example').DataTable( {
        lengthChange: false,
        buttons: [ 'copy', 'excel', 'pdf', 'colvis' ]
    } );
 
    table.buttons().container()
        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
} );
</script>
{% endblock %}

idil/templates/user_admin/edit.html
{%extends "user_admin/admin_base.html" %}
{% load static %}
{% block body_block %}
<header class="header">

    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">

            <a href="/user_admin/{{usr.username}}" class="navbar-brand">
                <img src="/static/img/logo.svg" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>

                
                <ul class="navbar-nav ml-auto">
                    <li id="navHone" class="nav-item ">
                        <a href="/user_admin/{{usr.username}}" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li id="navChallenge" class="nav-item">
                        <a href="/user_admin/add/{{usr.username}}" class="nav-link">Add New Challenges</a>
                    </li>
                    <li id="navBoard" class="nav-item">
                        <a href="/user_admin/acc/{{usr.username}}" class="nav-link">My Account</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li id="navuser2" class="nav-item " style="color: #fff">
                            <a href="{% url 'basic_app:user_logout' %}"class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Logout
                            </a>
                        </li>
                    {% endif %}
                </ul>         
            </div>
        </div>
    </nav>
</header>
<br>
<div class="card text-center" style="width:80%; margin-left : 10%">
  <div class="card-header" style="color:red;font-size:200%">
    <b>Challenge : {{ch.name}}</b>
  </div>
  <div class="card-body" >
    <form method="POST">
    {% csrf_token %}
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Challenge Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword" name="cn" value="{{ch.name}}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Technology</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputPassword" name="tech" value="{{ch.technology}}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Capability</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="cap" value="{{ch.capability}}" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Digital Points</label>
            <div class="col-sm-4">
                <input type="number" class="form-control" id="inputPassword" name="points" value="{{ch.points}}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Account</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="inputPassword" name="acc" value="{{ch.account}}" required>
                </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Applicant Status</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" id="inputPassword" name="astat" value="{{ch.applicant_status}}" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Expiry Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" id="inputPassword" name="edate" value="{{ch.expiry_date}}" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Challenge Category</label>
                <div class="col-sm-4">
                    <select class="form-control" id="inlineFormCustomSelectPref" name="cat" required>
                        <option value="WORKING" selected>{{ch.category}}</option>
                        <option value="WORKING" >WORKING</option>
                        <option value="LEARNING" >LEARNING</option>
                    </select>
                </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Manager</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="manager" value="{{ch.manager}}" required>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Product Owner</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="powner" value="{{ch.owner}}" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label" >Date Posted</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="D_p" value="{{ch.date_posted}}" disabled>
            </div>
            <label for="inputPassword" class="col-sm-2 col-form-label" >Applicants</label>
             <div class="col-sm-4">
                <input type="text" class="form-control" id="inputPassword" name="applicant" value="{{ch.applicant}}" required>
            </div>
        </div>
        
        <div class="form-group row">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label for="inputPassword" class="col-sm-2 col-form-label" >Project Description</label>
            <input type="text" class="form-control" style="width:81%;line-height:60px" id="exampleFormControlTextarea1" rows="3" name="desc" value="{{ch.desc}}" required></textarea>
        </div>
       
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" class="btn btn-outline-primary" value="UPDATE">
       
    </form>
  </div>
</div>
<br>
{% endblock %}